//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Config.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Config.xsd", IsNullable=false)]
public partial class Config {
    
    private ConfigSignalControler signalControlerField;
    
    /// <remarks/>
    public ConfigSignalControler SignalControler {
        get {
            return this.signalControlerField;
        }
        set {
            this.signalControlerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Config.xsd")]
public partial class ConfigSignalControler {
    
    private Structure[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private bool arField;
    
    private bool brField;
    
    private System.DateTime acGField;
    
    private string apfField;
    
    private System.DateTime acAField;
    
    private System.DateTime bcGField;
    
    private string bpfField;
    
    private System.DateTime bcAField;
    
    private System.DateTime sdField;
    
    public ConfigSignalControler() {
        this.arField = false;
        this.brField = false;
        this.acAField = new System.DateTime(0);
        this.bcAField = new System.DateTime(0);
        this.sdField = new System.DateTime(0);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AcA", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("AcG", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("AcR", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("AcY", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("ApG", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("ApR", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("Base", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BcA", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BcG", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BcR", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BcY", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BpG", typeof(Structure))]
    [System.Xml.Serialization.XmlElementAttribute("BpR", typeof(Structure))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public Structure[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AR {
        get {
            return this.arField;
        }
        set {
            this.arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool BR {
        get {
            return this.brField;
        }
        set {
            this.brField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime AcG {
        get {
            return this.acGField;
        }
        set {
            this.acGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Apf {
        get {
            return this.apfField;
        }
        set {
            this.apfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
    public System.DateTime AcA {
        get {
            return this.acAField;
        }
        set {
            this.acAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime BcG {
        get {
            return this.bcGField;
        }
        set {
            this.bcGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Bpf {
        get {
            return this.bpfField;
        }
        set {
            this.bpfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
    public System.DateTime BcA {
        get {
            return this.bcAField;
        }
        set {
            this.bcAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
    public System.DateTime sd {
        get {
            return this.sdField;
        }
        set {
            this.sdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Config.xsd")]
public partial class Structure {
    
    private string onLightStructureField;
    
    private string offLightStructureField;
    
    private string trackField;
    
    private double xField;
    
    private double yField;
    
    private double zField;
    
    private double rxField;
    
    private double ryField;
    
    private double rzField;
    
    private string tiltField;
    
    private double spanField;
    
    public Structure() {
        this.xField = 0D;
        this.yField = 0D;
        this.zField = 0D;
        this.rxField = 0D;
        this.ryField = 0D;
        this.rzField = 0D;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string OnLightStructure {
        get {
            return this.onLightStructureField;
        }
        set {
            this.onLightStructureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string OffLightStructure {
        get {
            return this.offLightStructureField;
        }
        set {
            this.offLightStructureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Track {
        get {
            return this.trackField;
        }
        set {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double Z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double RX {
        get {
            return this.rxField;
        }
        set {
            this.rxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double RY {
        get {
            return this.ryField;
        }
        set {
            this.ryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double RZ {
        get {
            return this.rzField;
        }
        set {
            this.rzField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Tilt {
        get {
            return this.tiltField;
        }
        set {
            this.tiltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Span {
        get {
            return this.spanField;
        }
        set {
            this.spanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Config.xsd", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    AcA,
    
    /// <remarks/>
    AcG,
    
    /// <remarks/>
    AcR,
    
    /// <remarks/>
    AcY,
    
    /// <remarks/>
    ApG,
    
    /// <remarks/>
    ApR,
    
    /// <remarks/>
    Base,
    
    /// <remarks/>
    BcA,
    
    /// <remarks/>
    BcG,
    
    /// <remarks/>
    BcR,
    
    /// <remarks/>
    BcY,
    
    /// <remarks/>
    BpG,
    
    /// <remarks/>
    BpR,
}
